name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Inject secrets
        run: |
          echo "const secrets = {" > secrets.js
          echo "    username: '${{ secrets.USERNAME }}'," >> secrets.js
          echo "    password: '${{ secrets.PASSWORD }}'" >> secrets.js
          echo "};" >> secrets.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
